language: objective-c
osx_image: xcode7.3

script:
  - touch syncthing/syncthing
  - xcodebuild test -configuration Debug -project syncthing-bar.xcodeproj -scheme syncthing-bar -destination 'platform=OS X,arch=x86_64'
